/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package visão.Curso;

import Controller.Controller_Curso;
import Dao.Dao_Entidades.Dao_Curso;
import Entidades.Cursos;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import org.hibernate.Session;

/**
 *
 * @author Tiago
 */
public class Novo_Curso extends javax.swing.JDialog {

    /**
     * Creates new form Novo_Curso
     */
    private Session sessão;
    private Cursos curso;
    private boolean altera;

    public Novo_Curso() {
        initComponents();
        super.setModal(true);
        this.setTitle("Novo Curso");
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.altera = false;

//        this.sessão = Hibernate_Sessao.getInstance().retornaSession();
    }

    public Novo_Curso(Session sessão, Cursos c) {
        initComponents();
        super.setModal(true);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.curso = c;
        this.sessão = sessão;
        this.setTitle("Alterar Curso");
        this.titulo.setText("Alteração de Curso");
        this.altera = true;
        preencheCampos();
    }

    private void preencheCampos() {
        this.codigoCurso.setText(this.curso.getCodigo());
        this.nomeCurso.setText(this.curso.getNome());
        this.turno.setSelectedItem(this.curso.getTurno());
    }

//    public static void main(String[] args) {
//        new Novo_Curso().setVisible(true);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        codigoCurso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        nomeCurso = new javax.swing.JTextField();
        inserirCurso = new javax.swing.JButton();
        cancelarCurso = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        turno = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titulo.setForeground(new java.awt.Color(255, 255, 255));
        titulo.setText("NOVO CURSO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(169, Short.MAX_VALUE)
                .addComponent(titulo)
                .addContainerGap(170, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(titulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        jLabel2.setText("Código*:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));
        getContentPane().add(codigoCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 77, 82, -1));

        jLabel3.setText("Nome*:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, -1, -1));

        nomeCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeCursoKeyReleased(evt);
            }
        });
        getContentPane().add(nomeCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(57, 115, 218, -1));

        inserirCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/salvar.png"))); // NOI18N
        inserirCurso.setText("Salvar");
        inserirCurso.setToolTipText("Salvar o Curso");
        inserirCurso.setMargin(new java.awt.Insets(2, 2, 2, 14));
        inserirCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirCursoActionPerformed(evt);
            }
        });
        getContentPane().add(inserirCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 165, -1, 34));

        cancelarCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        cancelarCurso.setText("Sair");
        cancelarCurso.setToolTipText("Sair da inserção de Curso");
        cancelarCurso.setMargin(new java.awt.Insets(2, 2, 2, 14));
        cancelarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(cancelarCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 166, 81, -1));

        jLabel4.setText("Turno*:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 118, -1, -1));

        turno.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "", "Diurno", "Integral", "Matutino", "Noturno" }));
        getContentPane().add(turno, new org.netbeans.lib.awtextra.AbsoluteConstraints(337, 115, 93, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirCursoActionPerformed
        // TODO add your handling code here:
        if (!altera) {
            curso = new Cursos();
        }
        Controller_Curso cc = new Controller_Curso();

        curso.setCodigo(this.codigoCurso.getText().toString());
        curso.setNome(this.nomeCurso.getText().toString());
        curso.setTurno(this.turno.getSelectedItem().toString());

        StringBuilder ver = cc.verificaCampos(this.curso);

        if (ver.length() == 0) {
            Dao_Curso dc = new Dao_Curso();

            boolean verDuplicidade = dc.retrievePorNome(curso.getCodigo(), curso.getNome(), curso.getTurno());

            if (verDuplicidade) {

                try {
//                Transaction tr = this.sessão.beginTransaction();
                    dc.persist(curso);
                    System.out.println("curso " + this.curso.getNome());
//                tr.commit();
//                sessão.flush();
                    limpaCampos();
                    JOptionPane.showMessageDialog(null, "Curso Inserido!");
                } catch (Exception ex) {
//                this.sessão.beginTransaction().rollback();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Já há um Curso cadastrado!");
            }
        } else {
            JOptionPane.showMessageDialog(null, ver);
        }
    }//GEN-LAST:event_inserirCursoActionPerformed

    private void cancelarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarCursoActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarCursoActionPerformed

    private void nomeCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeCursoKeyReleased
        // TODO add your handling code here:
        if (evt.getKeyChar() == 10) {
            inserirCursoActionPerformed(null);
        }
    }//GEN-LAST:event_nomeCursoKeyReleased

    private void limpaCampos() {
        this.codigoCurso.setText(null);
        this.nomeCurso.setText(null);
        this.turno.setSelectedIndex(0);
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Novo_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Novo_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Novo_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Novo_Curso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Novo_Curso().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarCurso;
    private javax.swing.JTextField codigoCurso;
    private javax.swing.JButton inserirCurso;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nomeCurso;
    private javax.swing.JLabel titulo;
    private javax.swing.JComboBox turno;
    // End of variables declaration//GEN-END:variables
}
